(self.AMP=self.AMP||[]).push({n:"amp-install-serviceworker",v:"1810152207300",f:(function(AMP,_){
function k(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,d);g&&Object.defineProperty(a,d,g)}else a[d]=b[d]}function l(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var m=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function n(a){var b=Object.create(null);if(!a)return b;for(var c;c=m.exec(a);){var d=l(c[1],c[1]),g=c[2]?l(c[2],c[2]):"";b[d]=g}return b};var p="";self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user};function t(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&u(b,"url")?v(b,"url"):null)return b}return w(a,"url")}function x(a){var b=y(a),b=z(b);return v(b,"documentInfo")}function w(a,b){a=y(a);a=z(a);return v(a,b)}function y(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=v(b,"ampdoc").getAmpDoc(a)}return a}function z(a){a=y(a);return a.isSingleDoc()?a.win:a}
function v(a,b){u(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function u(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function A(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function C(a){var b="A";if(a.closest)return a.closest(b);b=b.toUpperCase();return A(a,function(a){return a.tagName==b})};function D(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};var E;function F(a,b){var c=void 0,d=a,g=b,f;f=function(a){try{return g(a)}catch(B){throw self.reportError(B),B;}};var e=G(),h=!1;c&&(h=c.capture);d.addEventListener("click",f,e?c:h)}function G(){if(void 0!==E)return E;E=!1;try{var a={get capture(){E=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return E};function H(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function I(a){a=AMP.BaseElement.call(this,a)||this;a.c=null;a.w=null;return a}k(I,AMP.BaseElement);
I.prototype.buildCallback=function(){var a=this,b=this.win;if("serviceWorker"in b.navigator){var c=t(this.element),d=this.element.getAttribute("src");c.assertHttpsUrl(d,this.element);if(c.isProxyOrigin(d)||c.isProxyOrigin(b.location.href)){var g=this.element.getAttribute("data-iframe-src");if(g){c.assertHttpsUrl(g,this.element);var b=c.parse(g).origin,f=x(this.element).get(),e=c.parse(f.sourceUrl),h=c.parse(f.canonicalUrl);r().assert(b==e.origin||b==h.origin,"data-iframe-src (%s) should be a URL on the same origin as the source (%s) or canonical URL (%s) of the AMP-document.",
b,e.origin,h.origin);this.c=g;J(this).then(function(){return L(a)})}}else c.parse(b.location.href).origin==c.parse(d).origin?J(this).then(function(){return M(a.win,d)}):this.user().error("amp-install-serviceworker","Did not install ServiceWorker because it does not match the current origin: "+d)}else N(this)};function J(a){return Promise.all([a.loadPromise(a.win),w(a.getAmpDoc(),"viewer").whenFirstVisible()])}
function L(a){return a.mutateElement(function(){H(a.element);var b=a.win.document.createElement("iframe");b.setAttribute("sandbox","allow-same-origin allow-scripts");b.src=a.c;a.element.appendChild(b)})}
function N(a){if(a.getAmpDoc().isSingleDoc()){var b=a.getAmpDoc(),c=a.win,d=t(a.element),g=d.parse(c.location.href),f=a.element.getAttribute("data-no-service-worker-fallback-url-match"),e=a.element.getAttribute("data-no-service-worker-fallback-shell-url");if(f||e){r().assert(f&&e,'Both, "%s" and "%s" must be specified for url-rewrite',"data-no-service-worker-fallback-url-match","data-no-service-worker-fallback-shell-url");var e=D(e),h;try{h=new RegExp(f)}catch(K){throw r().createError('Invalid "data-no-service-worker-fallback-url-match" expression',
K);}r().assert(d.getSourceOrigin(g)==d.parse(e).origin,'Shell source origin "%s" must be the same as source origin "%s"',e,g.href);a.w=new O(b,h,e);d.isSecure(e)&&P(a,e)}}}function P(a,b){J(a).then(function(){a.mutateElement(function(){return Q(a,b)})})}
function Q(a,b){var c=a.win.document.createElement("iframe");c.id="i-amphtml-shell-preload";c.setAttribute("src",b+"#preload");H(c);c.setAttribute("sandbox","allow-scripts allow-same-origin");var d=a.loadPromise(c);d.then(function(){c.parentElement&&c.parentElement.removeChild(c)});a.element.appendChild(c)}function O(a,b,c){this.win=a.win;this.o=b;this.m=c;this.j=t(a);this.h=this.j.parse(c);a=a.getRootNode();b=this.l.bind(this);F(a,b)}
O.prototype.l=function(a){if(!a.defaultPrevented&&(a=C(a.target))&&a.href){var b=this.j.parse(a.href);if(b.origin==this.h.origin&&b.pathname!=this.h.pathname&&this.o.test(b.href)&&!a.getAttribute("i-amphtml-orig-href")){var c=this.win;D(b.href)!=D(c.location.href)&&(a.setAttribute("i-amphtml-orig-href",a.href),a.href=this.m+"#href="+encodeURIComponent(""+b.pathname+b.search+b.hash))}}};
function M(a,b){return a.navigator.serviceWorker.register(b).then(function(a){var b=self;if(b.AMP_MODE)b=b.AMP_MODE;else{var c=!!(self.AMP_CONFIG||{}).test||!1,f=n(b.location.originalHash||b.location.hash),e=n(b.location.search);p||(p=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"011810152207300");b=b.AMP_MODE={localDev:!1,development:!("1"!=f.development&&!b.AMP_DEV_MODE),examiner:"2"==f.development,filter:f.filter,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=e.amp_lite,test:c,log:f.log,
version:"1810152207300",rtvVersion:p}}b.development&&r().info("amp-install-serviceworker","ServiceWorker registration successful with scope: ",a.scope);return a},function(a){r().error("amp-install-serviceworker","ServiceWorker registration failed:",a)})}(function(a){a.registerElement("amp-install-serviceworker",I)})(self.AMP);
})});
//# sourceMappingURL=amp-install-serviceworker-0.1.js.map

