(self.AMP=self.AMP||[]).push({n:"amp-consent",v:"1810152207300",f:(function(AMP,_){
var g;function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function k(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ca=Object.prototype.toString;function l(a){return"[object Object]"===ca.call(a)}function da(a){return"number"===typeof a&&isFinite(a)}function m(a,b){for(var c in a)if(a[c]===b)return!0;return!1};self.log=self.log||{user:null,dev:null,userForEmbed:null};var n=self.log;function r(){if(!n.user)throw Error("failed to call initLogConstructor");return n.user}function t(){if(n.dev)return n.dev;throw Error("failed to call initLogConstructor");};var u=Object.prototype.hasOwnProperty;function v(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function w(a){return a||{}}
function ea(a,b){var c=1,c=void 0===c?10:c,d=[],e=[];e.push({t:a,s:b,d:0});for(b={};0<e.length;){var f=e.shift();b.t=f.t;b.s=f.s;b.d=f.d;if(d.includes(b.s))throw Error("Source object has a circular reference.");d.push(b.s);b.t!==b.s&&(b.d>c?Object.assign(b.t,b.s):(Object.keys(b.s).forEach(function(a){return function(b){var c=a.s[b];if(u.call(a.t,b)){var d=a.t[b];if(l(c)&&l(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(b)),b={s:b.s,t:b.t,d:b.d}))}return a};function x(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function y(a,b){a=a.__AMP_TOP||a;return z(a,b)}function B(a){a=C(a);a=D(a);return z(a,"viewer")}function E(a,b){a=D(a);var c=F(a,b);if(!c){var d=new x,c=d.promise,d=d.resolve;G(a)[b]={obj:null,promise:c,resolve:d,context:null,ctor:null}}b=c;return b}function C(a){return a.nodeType?y((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function D(a){a=C(a);return a.isSingleDoc()?a.win:a}
function z(a,b){var c=G(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function F(a,b){var c=G(a)[b];if(c){if(c.promise)return c.promise;z(a,b);return c.promise=Promise.resolve(c.obj)}return null}function G(a){var b=a.services;b||(b=a.services={});return b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function H(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var I;function fa(a){var b=C(a),c=F(D(a),"geo");return c?c:b.whenBodyAvailable().then(function(){var a;a=b.win;var c=b.getHeadNode(),f;if(c){f=[];for(var c=c.querySelectorAll("script[custom-element]"),h=0;h<c.length;h++)f.push(c[h].getAttribute("custom-element"))}else f=[];a=f.includes("amp-geo")?y(a,"extensions").waitForExtension(a,"amp-geo"):Promise.resolve();return a}).then(function(){return F(D(a),"geo")})};function J(a){this.pa=a;this.X=this.fa=0;this.L=Object.create(null)}J.prototype.has=function(a){return!!this.L[a]};J.prototype.get=function(a){var b=this.L[a];if(b)return b.access=++this.X,b.payload};J.prototype.put=function(a,b){this.has(a)||this.fa++;this.L[a]={payload:b,access:this.X};if(!(this.fa<=this.pa)){t().warn("lru-cache","Trimming LRU cache");a=this.L;var c=this.X+1,d,e;for(e in a){var f=a[e].access;f<c&&(c=f,d=e)}void 0!==d&&(delete a[d],this.fa--)}};var K=self.AMP_CONFIG||{},ga={thirdParty:K.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:K.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof K.thirdPartyFrameRegex?new RegExp(K.thirdPartyFrameRegex):K.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:K.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof K.cdnProxyRegex?new RegExp(K.cdnProxyRegex):K.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:K.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:K.localDev||!1};var ha=w({c:!0,v:!0,a:!0,ad:!0}),L,M,ia=/[?&]amp_js[^&]*/,ja=/[?&]amp_gsa[^&]*/,ka=/[?&]amp_r[^&]*/,la=/[?&]usqp[^&]*/;
function N(a){var b;L||(L=self.document.createElement("a"),M=self.UrlCache||(self.UrlCache=new J(100)));var c=b?null:M,d=L;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function ma(a){"string"==typeof a&&(a=N(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function O(a,b){var c;c=void 0===c?"source":c;r().assert(null!=a,"%s %s must be available",b,c);var d=a;r().assert(ma(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d}
function na(a){"string"==typeof a&&(a=N(a));var b=a;"string"==typeof b&&(b=N(b));if(!ga.cdnProxyRegex.test(b.origin))return a.href;var b=a.pathname.split("/"),c=b[1];r().assert(ha[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);r().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(ia,"").replace(ja,"").replace(ka,"").replace(la,"").replace(/^[?&]/,
""))?"?"+c:"":"";return b+c+(a.hash||"")}function oa(a,b){"string"==typeof b&&(b=N(b));var c;if("function"==typeof URL)c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=N(d));c=c.replace(/\\/g,"/");var e=N(c);c=H(c.toLowerCase(),e.protocol)?e.href:H(c,"//")?d.protocol+c:H(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c};function pa(a){if(null==I){var b=a.ownerDocument;try{var c=b.createElement("div"),d=b.createElement("div");c.appendChild(d);I=c.querySelector(":scope div")===d}catch(f){I=!1}}I?a=a.querySelectorAll(":scope > script"):(a.classList.add("i-amphtml-scoped"),b=a.querySelectorAll(".i-amphtml-scoped > script"),a.classList.remove("i-amphtml-scoped"),a=b);if(1!==a.length)throw Error("Found "+a.length+" <script> children. Expected 1.");var e=a[0];a=e;if("SCRIPT"!=a.tagName||!a.hasAttribute("type")||"APPLICATION/JSON"!=
a.getAttribute("type").toUpperCase())throw Error('<script> child must have type="application/json"');try{return JSON.parse(e.textContent)}catch(f){throw Error("Failed to parse <script> contents. Is it valid JSON?");}};function P(a,b){var c;if(a.__AMP__EXPERIMENT_TOGGLES)c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var e=
e.getAttribute("content").split(","),f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0);Object.assign(c,qa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var h;h=ba.exec(e);)f=k(h[1],h[1]),h=h[2]?k(h[2],h[2]):"",a[f]=h;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}var p=c;return!!p[b]}
function qa(a){a:{var b;try{b=a.document.cookie}catch(h){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==k(c.substring(0,d).trim(),void 0)){a=c.substring(d+1).trim();a=k(a,a);break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};function Q(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function R(){this.w=null}g=R.prototype;g.add=function(a){var b=this;this.w||(this.w=[]);this.w.push(a);return function(){b.remove(a)}};g.remove=function(a){this.w&&(a=this.w.indexOf(a),-1<a&&this.w.splice(a,1))};g.removeAll=function(){this.w&&(this.w.length=0)};g.fire=function(a){if(this.w)for(var b=this.w,c=0;c<b.length;c++)(0,b[c])(a)};g.getHandlerCount=function(){return this.w?this.w.length:0};function S(){this.G=0;this.la=Promise.resolve();this.ja=function(){};this.ka=function(){}}S.prototype.onQueueEmpty=function(a){this.ja=a;0==this.G&&a()};S.prototype.onQueueNotEmpty=function(a){this.ka=a;0<this.G&&a()};S.prototype.registerUI=function(a){var b=this;0==this.G&&this.ka();this.G++;var c=this.la.then(function(){return a().then(function(){b.G--;0==b.G&&b.ja()})});return this.la=c};var T={};var ra={ACCEPTED:1,REJECTED:2,DISMISSED:3,NOT_REQUIRED:4,UNKNOWN:5};function U(a){this.o=a;this.h={};this.M={};this.O={};this.N={}}g=U.prototype;g.registerConsentInstance=function(a,b){this.h[a]?t().error("CONSENT-STATE-MANAGER","instance "+a+" already registered"):(this.h[a]=new V(this.o,a,b),this.M[a]=new R,this.O[a]&&(this.O[a](),this.N[a]=null,this.O[a]=null))};
g.updateConsentInstanceState=function(a,b){this.h[a]&&this.M[a]?(this.M[a].fire(b),this.h[a].update(b)):t().error("CONSENT-STATE-MANAGER","instance "+a+" not registered")};g.getConsentInstanceState=function(a){return this.h[a].get()};g.onConsentStateChange=function(a,b){var c=this.M[a].add(b);this.getConsentInstanceState(a).then(function(a){b(a)});return c};g.setConsentInstanceSharedData=function(a,b){this.h[a].sharedDataPromise=b};g.getConsentInstanceSharedData=function(a){return this.h[a].sharedDataPromise};
g.whenConsentReady=function(a){if(this.h[a])return Promise.resolve();if(!this.N[a]){var b=new x;this.N[a]=b.promise;this.O[a]=b.resolve}return this.N[a]};function V(a,b,c){this.o=a;this.ra=b;this.sharedDataPromise=null;this.na=E(a,"storage");this.m=null;this.ma="amp-consent:"+b;(this.S=c.onUpdateHref||null)&&O(this.S,"AMP-CONSENT")}
V.prototype.update=function(a){var b=this;m(ra,a)||(a=5);if(3==a)this.m=this.m||5;else if(4==a)this.m&&5!=this.m||(this.m=4);else if(a!==this.m&&(this.m=a,5!=a)){var c=1==a;this.na.then(function(d){a==b.m&&(d.set(b.ma,c),sa(b,c))})}};
V.prototype.get=function(){var a=this;return this.m?Promise.resolve(this.m):this.na.then(function(b){return b.get(a.ma)}).then(function(b){if(a.m)return a.m;a.m=void 0===b?5:b?1:2;return a.m}).catch(function(a){t().error("CONSENT-STATE-MANAGER","Failed to read storage",a);return 5})};
function sa(a,b){if(a.S){var c=E(a.o,"cid").then(function(a){return a.get({scope:"AMP-CONSENT",createCookieIfNotPresent:!0},Promise.resolve())});c.then(function(c){var d={credentials:"include",method:"POST",body:{consentInstanceId:a.ra,ampUserId:c,consentState:b},ampCors:!1};B(a.o).whenFirstVisible().then(function(){y(a.o.win,"xhr").fetchJson(a.S,d)})})}};var ta={"default":!0,_till_responded:!0,_till_accepted:!0,_auto_reject:!0};function ua(a){this.o=a;this.U=v();this.T=v();this.h=v();this.ha=E(this.o,"consentStateManager");a=new x;this.oa=a.promise;this.Y=a.resolve}function W(a){return P(a,"multi-consent")}g=ua.prototype;
g.registerConsentPolicyInstance=function(a,b){var c=this;this.h[a]&&t().error("consent-policy-manager","policy "+a+" already registered");var d=Object.keys(b.waitFor||{}),e=new va(b);this.h[a]=e;this.T[a]&&(this.T[a](),this.T[a]=null,this.U[a]=null);var f=[];this.ha.then(function(a){for(var b={},h=0;h<d.length;b={consentId:b.consentId,resolver:b.resolver},h++){b.consentId=d[h];var A=new x,Aa=A.promise;b.resolver=A.resolve;a.whenConsentReady(b.consentId).then(function(b){return function(){a.onConsentStateChange(b.consentId,
function(a){b.resolver&&(b.resolver(),b.resolver=null);e.consentStateChangeHandler(b.consentId,a)})}}(b));f.push(Aa)}c.oa.then(function(){Promise.all(f).then(function(){e.startTimeout(c.o.win)})})})};g.enableTimeout=function(){this.Y&&this.Y();this.Y=null};
g.whenPolicyResolved=function(a){var b=this;return W(this.o.win)||ta[a]?wa(this,a).then(function(){return b.h[a].getReadyPromise().then(function(){return b.h[a].getCurrentPolicyStatus()})}):(r().error("consent-policy-manager","can not find defined policy "+a+", only supported predefined policy supported now"),Promise.resolve(4))};
g.whenPolicyUnblock=function(a){var b=this;return W(this.o.win)||ta[a]?wa(this,a).then(function(){return b.h[a].getReadyPromise().then(function(){return b.h[a].shouldBlock()})}):(r().error("consent-policy-manager","can not find defined policy "+a+", only supported predefined policy supported now"),Promise.resolve(!1))};
g.getMergedSharedData=function(a){var b=this;return this.whenPolicyResolved(a).then(function(){return b.ha}).then(function(c){var d=b.h[a].getConsentInstanceIds().map(function(a){return c.getConsentInstanceSharedData(a)});return Promise.all(d)}).then(function(a){a.unshift({});return Object.assign.apply(null,a)})};function wa(a,b){if(a.h[b])return Promise.resolve();if(!a.U[b]){var c=new x;a.U[b]=c.promise;a.T[b]=c.resolve}return a.U[b]}
function va(a){var b=Object.keys(a.waitFor||{});this.qa=a;this.l=v();var c=new x;this.sa=c.promise;this.ea=c.resolve;this.ga=4;this.ua=a.unblockOn||[1,3];this.I(b)}g=va.prototype;g.I=function(a){for(var b=0;b<a.length;b++)this.l[a[b]]=null};g.getConsentInstanceIds=function(){return Object.keys(this.l)};
g.startTimeout=function(a){var b=this,c=this.qa.timeout,d=null,e;void 0!=c&&(l(c)?(c.fallbackAction&&"reject"==c.fallbackAction?e=2:c.fallbackAction&&"dismiss"!=c.fallbackAction&&r().error("consent-policy-manager","unsupported fallbackAction "+c.fallbackAction),d=c.seconds):d=c,r().assert(da(d),"invalid timeout value "+d));null!=d&&a.setTimeout(function(){xa(b,!0,e)},1E3*d)};
g.consentStateChangeHandler=function(a,b){if(!u.call(this.l,a))t().error("consent-policy-manager","cannot find "+a+" in policy state");else if(5!=b){if(4==b){var c=1!=this.l[a]&&2!=this.l[a];c&&(this.l[a]=4)}else 3==b?null===this.l[a]&&(this.l[a]=5):this.l[a]=b;xa(this)}};
function xa(a,b,c){b=void 0===b?!1:b;for(var d=!0,e=!0,f=!1,h=Object.keys(a.l),p=0;p<h.length;p++){var q=h[p];if(null===a.l[q])if(b)a.l[q]=c||5;else return;4==a.l[q]&&(d=!1);2==a.l[q]&&(e=d=!1);5==a.l[q]&&(e=d=!1,f=!0)}a.ga=d?1:e?3:f?4:2;a.ea&&(a.ea(),a.ea=null)}g.getReadyPromise=function(){return this.sa};g.getCurrentPolicyStatus=function(){return this.ga};g.shouldBlock=function(){return-1<this.ua.indexOf(this.ga)};function X(a,b,c){this.Z=a;this.da=this.R=!1;this.C=null;this.o=a.getAmpDoc();this.F=a.element;this.va=a.win;this.I(b,c)}
X.prototype.I=function(a,b){if(b){var c=this.o.getElementById(b);c||r().error("amp-consent-ui","postPromptUI element with "+("id="+b+" not found"));this.C=c;this.da=!0}else{var d=a.promptUI,e=a.promptUISrc;if(d){var f=this.o.getElementById(d);f&&this.F.contains(f)||r().error("amp-consent-ui","child element of <amp-consent> with "+("promptUI id "+d+" not found"));this.C=f}else e&&P(this.va,"amp-consent-v2")&&(this.R=!0,a=this.F.ownerDocument.createElement("iframe"),a.src=O(e,this.F),a.setAttribute("sandbox",
"allow-scripts"),this.C=a)}};X.prototype.show=function(){if(this.C){Q(this.F,!0);var a=this.F.classList;a.add("amp-active");a.remove("amp-hidden");this.Z.getViewport().addToFixedLayer(this.F);Q(this.C,!0);if(this.R){var b=this.F;b.insertBefore(this.C,b.firstChild)}this.da||this.R||this.Z.scheduleLayout(this.C)}};
X.prototype.hide=function(){if(this.C){if(!this.da){var a=this.F.classList;a.remove("amp-active");a.add("amp-hidden")}this.Z.getViewport().removeFromFixedLayer(this.F);Q(this.C,!1);this.R&&(a=this.C,a.parentElement&&a.parentElement.removeChild(a))}};var ya={ACCEPT:"accept",REJECT:"reject",DISMISS:"dismiss"};function Y(a){a=AMP.BaseElement.call(this,a)||this;a.D=null;a.$=null;a.J=null;a.H=v();a.A={};a.B={};a.ia=v();a.j=null;a.V=null;a.P=v();a.aa=v();a.ba=!1;a.W=a.getVsync();a.ca=!1;a.K=v();return a}aa(Y,AMP.BaseElement);Y.prototype.getConsentPolicy=function(){return null};
Y.prototype.buildCallback=function(){var a=this;this.ba=W(this.win);r().assert(this.element.getAttribute("id"),"amp-consent should have an id");var b;try{b=pa(this.element)}catch(A){throw this.user().createError("amp-consent",A);}var c=b,d=za(this);b=ea(d||{},c||{});Ba(this,b);b=this.getRealChildren();for(var e=0;e<b.length;e++){var f=b[e];Q(f,!1);this.setAsOwner(f)}var h=E(this.getAmpDoc(),"consentPolicyManager").then(function(b){a.$=b;var c=Object.keys(a.A);b={};for(var d=0;d<c.length;d++)b[c[d]]=
void 0;var c={waitFor:b},d=[4,1,2,3],e={waitFor:b,timeout:{seconds:0,fallbackAction:"reject"},unblockOn:d};a.B._till_responded={waitFor:b,unblockOn:d};a.B._till_accepted=c;a.B._auto_reject=e;a.B&&a.B["default"]||(a.B["default"]=c);var f=Object.keys(a.B);for(b=0;b<f.length;b++)a.$.registerConsentPolicyInstance(f[b],a.B[f[b]])}),p=E(this.getAmpDoc(),"consentStateManager").then(function(b){a.D=b}),q=E(this.getAmpDoc(),"notificationUIManager").then(function(b){a.J=b});Promise.all([p,q,h]).then(function(){a.I()})};
function Ca(a){a.registerAction("accept",function(){return Z(a,"accept")});a.registerAction("reject",function(){return Z(a,"reject")});a.registerAction("dismiss",function(){return Z(a,"dismiss")});a.registerAction("prompt",function(b){var c=b.args,d=c&&c.consent;a.ba||(d=Object.keys(a.A)[0]);d=d||"";r().assert(a.A[d],"consent with id "+d+" not found");Da(a,d)});Ea(a)}
function Ea(a){a.win.addEventListener("message",function(b){if(a.j){var c=b.data;if(c&&"consent-response"==c.type)if(c.action)for(var d=a.element.querySelectorAll("iframe"),e=0;e<d.length;e++){if(d[e].contentWindow===b.source){var f=c.action;Z(a,f);break}}else r().error("amp-consent","consent-response message missing required info")}})}function Da(a,b){a.J||t().error("amp-consent","notification ui manager not found");!a.aa[b]&&a.H[b]&&(a.aa[b]=!0,a.J.registerUI(a.ta.bind(a,b)))}
Y.prototype.ta=function(a){var b=this;this.j&&t().error("amp-consent","other consent instance on display "+this.j);this.W.mutate(function(){b.j=a;b.H[b.j].show()});var c=new x;this.P[a]=c.resolve;return c.promise};function Fa(a){a.j&&a.H[a.j]||t().error("amp-consent",a.j+" no consent ui to hide");var b=a.H[a.j];a.W.mutate(function(){b.hide()});var c=a.j;a.P[c]&&(a.P[c](),a.P[c]=null);a.aa[c]=!1;a.j=null}
function Z(a,b){m(ya,b)&&a.j&&(a.D?("accept"==b?a.D.updateConsentInstanceState(a.j,1):"reject"==b?a.D.updateConsentInstanceState(a.j,2):"dismiss"==b&&a.D.updateConsentInstanceState(a.j,3),Fa(a)):t().error("amp-consent","No consent state manager"))}
Y.prototype.I=function(){for(var a=this,b=Object.keys(this.A),c=[],d={},e=0;e<b.length;d={instanceId:d.instanceId},e++){d.instanceId=b[e];this.D.registerConsentInstance(d.instanceId,this.A[d.instanceId]);Ga(this,d.instanceId);var f=Ha(this,d.instanceId,this.A[d.instanceId]),h=f.then(function(b){return function(){return Ia(a,b.instanceId)}}(d)).catch(function(){});c.push(h)}Promise.all(c).then(function(){Ja(a);a.$.enableTimeout()});Ca(this)};
function Ha(a,b,c){r().assert(c.checkConsentHref||c.promptIfUnknownForGeoGroup,"neither checkConsentHref nor promptIfUnknownForGeoGroup is defined");var d=null;if(c.promptIfUnknownForGeoGroup)var e=c.promptIfUnknownForGeoGroup,d=Ka(a,e);else d=La(a,b).then(function(b){return b&&u.call(b,"promptIfUnknown")?!!b.promptIfUnknown:(a.user().error("amp-consent","Expecting promptIfUnknown from checkConsentHref when promptIfUnknownForGeoGroup is not specified"),!1)});return d.then(function(c){a.ia[b]=!!c})}
function Ga(a,b){var c=La(a,b),d=c.then(function(a){return a&&void 0!==a.sharedData?a.sharedData:null});a.D.setConsentInstanceSharedData(b,d)}function Ka(a,b){return fa(a.element).then(function(a){r().assert(a,"requires <amp-geo> to use promptIfUnknownForGeoGroup");return 0<=a.ISOCountryGroups.indexOf(b)})}
function La(a,b){if(a.K[b])return a.K[b];if(a.A[b].checkConsentHref){var c={credentials:"include",method:"POST",body:{consentInstanceId:b},requireAmpResponseSourceOrigin:!1},d=a.A[b].checkConsentHref;O(d,a.element);var e=a.getAmpDoc(),f=na(e.getUrl()),h=oa(d,f),p=B(e);a.K[b]=p.whenFirstVisible().then(function(){return y(a.win,"xhr").fetchJson(h,c).then(function(a){return a.json()})})}else a.K[b]=Promise.resolve(null);return a.K[b]}
function Ba(a,b){var c=b.consents;r().assert(c,"amp-consent: consents config is required");r().assert(0!=Object.keys(c).length,"amp-consent: can't find consent instance");if(!a.ba&&(r().assert(1>=Object.keys(c).length,"amp-consent: only single consent instance is supported"),b.policy))for(var d=Object.keys(b.policy),e=0;e<d.length;e++)"default"!=d[e]&&(r().warn("amp-consent","policy "+d[e]+" is currently not supportedand will be ignored"),delete b.policy[d[e]]);a.A=c;b.postPromptUI&&(a.V=new X(a,
w({}),b.postPromptUI));a.B=b.policy||a.B}function za(a){if(!P(a.win,"amp-consent-v2"))return null;a=a.element.getAttribute("type");if(!a)return null;r().assert(T[a],"invalid CMP type "+a);var b=T[a];a=["consentInstanceId","checkConsentHref","promptUISrc"];for(var c=0;c<a.length;c++);var d=b.consentInstanceId;a=w({consents:w({})});c=Object.assign({},b);delete c.consentInstanceId;a.consents[d]=c;return a}
function Ia(a,b){a.H[b]=new X(a,a.A[b]);return a.D.getConsentInstanceState(b).then(function(c){if(1==c||2==c)a.ca=!0;5==c&&(a.ia[b]?(a.ca=!0,Da(a,b)):a.D.updateConsentInstanceState(b,4))})}function Ja(a){a.ca&&a.V&&(a.J.onQueueEmpty(function(){a.W.mutate(function(){a.V.show()})}),a.J.onQueueNotEmpty(function(){a.W.mutate(function(){a.V.hide()})}))}
(function(a){a.registerElement("amp-consent",Y,"amp-consent{position:fixed;bottom:0;left:0;overflow:hidden!important;background:hsla(0,0%,100%,0.7);z-index:1000;width:100%}amp-consent[i-amphtml-notbuilt]>*{display:none!important}amp-consent>*{max-height:100vh!important}amp-consent.amp-active{visibility:visible}amp-consent.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-consent/0.1/amp-consent.css*/");a.registerServiceForDoc("notificationUIManager",S);a.registerServiceForDoc("consentStateManager",
U);a.registerServiceForDoc("consentPolicyManager",ua)})(self.AMP);
})});
//# sourceMappingURL=amp-consent-0.1.js.map

