window.SPR=function(){function z(a,d){var c=this;c.M=[];c.G=a||{};c.gd=b.Nc;c.sa=!1;c.Fc=d||b.oc;p.jc(c.Fc);h.a(a[b.ta]);a[b.b]=a[b.b]||q.current[b.b];a[b.url]=a[b.url]||e.la();a[b.title]||(a[b.title]=e.ka(a[b.url]));if(a[b.url])c.a=function(){if(c.Bc())return c.fc(),c;h[b.error](c.Mb());return null},c[b.Qc]=function(a){c.Cc(a)?c.gc(a):c.Ib(a);return c},c[b.Ic]=function(a){c.zc(a)?c.ec(a):c.Hb();return c},c[b.Vc]=function(a){c.Dc(a)?c.hc(a):c.Jb();return c},c[b.Gc]=function(){c.sa||(c.v(c.ha(c.ha())),
c[b.Ia](100),c.sa=!0);return c},c[b.Ia]=function(a){if(g.contains(c.M,a))return null;if(g.contains(g.$,a)){var d=c.j();d[b.m]=b.Ja;d[b.Ja]=c.qb(a);c.v(d)}else h[b.error](b.xb);return c},c.qb=function(a){var d,l=g.$,e={};if(!g.contains(l,a))h[b.error](b.va);else if(!g.contains(c.M,a))for(d=0;d<l.length;d+=1){var m=l[d];a>=m&&!g.contains(c.M,m)&&(c.M.push(m),e[m]=!0,h[b.info](b.Ca+m))}return e},c.v=function(a){p.i(b.l,b.Kc,a)},c.fc=function(){c.v(c.vb())},c.kd=function(){return q.current},c.j=function(){return v.ea(c.G)},
c.vb=function(){var a=c.j();a[b.m]=b.Mc;return a},c.Bc=function(){var a;for(a=0;a<r.length;a+=1)if(!c.G[r[a]])return!1;return!0},c.Mb=function(){var a,d=[];for(a=0;a<r.length;a+=1)c.G[r[a]]||d.push(r[a]);return b.zb+d.join(", ")},c.gc=function(a){c.v(c.rc(a))},c.Cc=function(a){return a===b.Tc||a===b.Uc},c.rc=function(a){var d=c.j();d[b.m]=b.Rc;d[b.Sc]=a;return d},c.Ib=function(a){if(a)h[b.error](a+b.Ab);else h[b.error](b.xc)},c.ha=function(){var a=c.j();a[b.m]=b.Hc;return a},c.ec=function(a){c.v(c.mb(a))},
c.mb=function(a){var d=c.j();d[b.m]=b.Jc;d[b.Oc]=a;return d},c.zc=function(a){return!isNaN(a)},c.Hb=function(){h[b.error](b.wb)},c.hc=function(a){c.v(c.sc(a))},c.sc=function(a){var d=c.j();d[b.m]=b.Wc;d[b.Pc]=a;return d},c.Dc=function(a){return!isNaN(a)&&c.Ec(a)},c.Ec=function(a){return g.cb(g.Xc,a)},c.Jb=function(){h[b.error](b.yb)};else h[b.error](b.ca+b.ma)}var b={l:"edge.simplereach.com",version:"2.16.0",ab:"d8rk54i4mohrb.cloudfront.net",ub:"/n",tc:"/t",Kc:"/v",na:"/event",Ya:"/pixel?bad=true&error=",ed:"/iframe.html",
bb:"/container.html",Ea:"000000000000000000000000",ca:"SPR-ERROR: ",ma:"100 - Missing url",Xb:"__reach_config",Za:"cache_buster",Aa:"__srret",Ha:"__srui",P:"0",Rb:"1",tb:"img",Sb:"1px",width:"width",c:"undefined",error:"error",Nb:"off",info:"info",J:"SPR_DEBUG",Da:"//",da:"string",referrer:"referrer",uid:"uid",R:"callback",i:"jsonp",url:"url",title:"title",b:"pid",ua:"ignore_metadata",Lb:"meta",o:"property",name:"name",$a:"canonical",link:"link",rel:"rel",Yc:"article",Pb:"og:url",wc:"twitter:url",
Ob:"og:title",vc:"twitter:title",Sa:"article:published_at",Va:"article:sr_published_at",Qa:"article:author",Ta:"article:sr_author",Xa:"article:tag",Wa:"article:sr_tag",Ra:"article:section",Ua:"article:sr_section",Ba:"s",r:"r",t:"t",e:"e",x:"x",n:"n",yc:"v",ta:"ignore_errors",Wb:"preview",A:"authors",B:"channels",K:"tags",h:"date",fd:"inframe",Na:"ajax",pc:"social_tracking",dd:"iframe",fb:"custom_tracking",Yb:"reach_tracking",u:"ref_url",Z:"page_url",pd:"user_id",Kb:"manual_scroll_depth",ja:"content_height",
jd:"rd",cd:"fb",Zc:"de",Tb:"pi",eb:"csd",Ub:"partners-api.pinterest.com",Vb:"/v1/urls/count.json",va:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",Ca:"[info] sending scrollDepth of: ",dc:"[info] scroll depth not activated, not sending data",oc:"SimplereachVideo",m:"event_name",zb:"Missing params please provide a ",Ab:" is not a valid start event type.",xc:"Cannot have an undefined start type. Please provide a start type.",wb:"Please pass a valid number",xb:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",
ld:"[error] Quartile for this video already sent",yb:"Please pass a valid threshold number",Lc:"video_id",Gb:"length",description:"description",od:"thumbnail_url",md:"source_url",ya:"networks",Nc:"video",Qc:"start",Ic:"elapsed",Gc:"complete",Ia:"quartile",Vc:"elapsedThreshold",Mc:"init",Rc:"start",Jc:"elapsed",Ja:"quartile",Hc:"complete",Wc:"elapsed_threshold",Sc:"start_type",Tc:"auto",Uc:"click",Oc:"seconds_elapsed",Pc:"threshold"},g={bc:function(){return Math.random().toString(36).replace(/[^a-z]+/g,
"")},returnValue:function(a){return a},X:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},Cb:function(a){return"[object String]"===Object.prototype.toString.call(a)},O:function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},xa:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+",")},cb:function(a,
b){if(!isNaN(b)&&!this.Cb(b))for(var c=0;c<=a.length;c++)if(a[c]===b)return!0;return!1},U:function(a){typeof a===b.da&&(a=a.split(","));if(this.X(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.da&&(a[d]=a[d].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},F:function(){},pa:function(){return window.location.protocol+"//"},$:[25,50,75,100],Xc:[3,15,30,45]},t={encode:function(a,b){var c=[];if(g.X(a))for(var d=0,f;d<a.length;d+=1)f=a[d],/\[\]$/.test(b)?c.push(encodeURIComponent(b)+
"="+encodeURIComponent(f)):c.push(this.encode(f,b+"["+("object"===typeof f?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(b?c.push(this.encode(a[d],b+"["+d+"]")):c.push(this.encode(a[d],d)));return c.join("&")},decode:function(a){var d={},c=0,l={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var f=a[c].split("="),e=decodeURIComponent(f[0]),
h=d,m=0,n=e.split("]["),k=n.length-1;/\[/.test(n[0])&&/\]$/.test(n[k])?(n[k]=n[k].replace(/\]$/,""),n=n.shift().split("[").concat(n),k=n.length-1):k=0;if(2===f.length)if(f=(f=decodeURIComponent(f[1]))&&!isNaN(f)?+f:f===b.c?void 0:void 0!==l[f]?l[f]:f,k)for(;m<=k;m+=1)e=""===n[m]?h.length:n[m],h=h[e]=m<k?h[e]||(n[m+1]&&isNaN(n[m+1])?{}:[]):f;else g.X(d[e])?d[e].push(f):d[e]=void 0!==d[e]?[d[e],f]:f;else e&&(d[e]=void 0)}return d}},u={za:{},ra:function(a){var b=document.cookie||"",c=this.za[a];c||(c=
a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.za[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},ba:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());document.cookie=a+"="+b+d+"; path=/"},$c:function(a){this.ba(a,"",new Date(1982,5,13))}},q={current:{}},h={oa:!1,info:g.F,error:g.log,a:function(){window[b.J]&&(this.oa=!0,window[b.J][b.info]&&(this[b.info]=window[b.J][b.info]),window[b.J][b.error]&&(this[b.error]=window[b.J][b.error]))},
reset:function(){this.oa=!1;this[b.info]=g.F;this[b.info]=g.log},lc:function(a){var d=document.createElement(b.tb);d.src=g.pa()+b.l+b.Ya+a.message;d.setAttribute(b.width,b.Sb);document.body?document.body.appendChild(d):document.head.appendChild(d)},mc:function(a){a===b.info?(this[b.info]=g.log,this[b.error]=g.log):a===b.error?(this[b.info]=g.F,this[b.error]=g.log):(this[b.info]=g.F,this[b.error]=g.F)}},e={P:0,D:{x:0,y:0},W:!0,a:function(){function a(){l.W=document[f]?!1:!0}function d(){l.flush();
window.removeEventListener("DOMContentLoaded",d,!1)}function c(){/loaded|interactive|complete/.test(document.readyState)&&(document.detachEvent("onreadystatechange",c),g&&(g=!1,l.flush()))}var l=this;l.P=0;this.Qb(window,"mousemove",function(a){l.D={x:a.clientX,y:a.clientY}});if(typeof document.hidden!==b.c){var f="hidden";var e="visibilitychange"}else typeof document.mozHidden!==b.c?(f="mozHidden",e="mozvisibilitychange"):typeof document.msHidden!==b.c?(f="msHidden",e="msvisibilitychange"):typeof document.webkitHidden!==
b.c&&(f="webkitHidden",e="webkitvisibilitychange");typeof document.addEventListener!==b.c&&typeof f!==b.c&&document.addEventListener(e,a,!1);var g=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",d,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Ka:function(a,d){var c=document.createElement("iframe"),e=document.body;c.setAttribute("name","spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id",
"spr-iframe-"+d);c.style.display="none";e||(e=this.g("BODY")[0]);e||(e=this.g("HEAD")[0]);h[b.info](a);e.appendChild(c);return c},ib:function(){return this.f(this,b.o,b.Pb)},gb:function(){return this.ob(this,b.$a)},jb:function(){return this.f(this,b.name,b.wc)},kb:function(){return window.location.protocol+b.Da+window.location.hostname+window.location.pathname},la:function(){return this.gb()||this.ib()||this.jb()||this.kb()},hb:function(){return this.f(this,b.o,b.Va)||this.f(this,b.o,b.Sa)},V:function(a,
d){return this.f(this,b.o,a)||this.f(this,b.o,d)},qa:function(){return document.referrer},ka:function(a){return this.f(this,b.o,b.Ob)||this.f(this,b.name,b.vc)||document.title||a||!1},ob:function(a,d){a=a.g(b.link);for(var c=0;c<a.length;c++)if(a[c].rel===d)return a[c].href},f:function(a,d,c){a=a.g(b.Lb);for(var e=[],f=0;f<a.length;f++)a[f].getAttribute(d)===c&&e.push(a[f].content);if(e.length)return 1==e.length?e[0]:e},Zb:function(a){var b=document.body,c=this.g("BODY")[0],e=this.g("HEAD")[0];b&&
b.contains(a)?b.removeChild(a):c&&c.contains(a)?c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);return a},La:function(a){var d=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id","spr-script");c.src=a;h[b.info](a);this.Y(function(){setTimeout(function(){d.g("HEAD")[0].appendChild(c)},1)});return c},s:[],ready:/loaded|interactive|complete/.test(document.readyState),flush:function(){var a=this.s.shift();for(this.ready=
!0;a;)a(),a=this.s.shift()},Y:function(a){/loaded|interactive|complete/.test(document.readyState)?(this.s.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function c(){if(!document.uniqueID&&document.expando)return this.s.push(a);try{document.documentElement.doScroll("left"),a()}catch(l){setTimeout(c,0)}}():this.s.push(a):this.s.push(a)},Qb:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},Nb:function(a,b,c){a.addEventListener?
a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},N:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.P},g:function(a){var b=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));break;case ".":var f=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<f.length;c+=1)a=(" "+f[c].className+" ").replace(/[\n\t\r]/g," "),-1<
a.indexOf(e)&&b.push(f[c]);break;default:b=document.getElementsByTagName(a)}return b}},v={ea:function(a){var d;var c=g.O(a);c[b.A]&&(c[b.A]=g.U(c[b.A]));c[b.B]&&(c[b.B]=g.U(c[b.B]));c[b.K]&&(c[b.K]=g.U(c[b.K]));c[b.h]&&typeof c[b.h]!==b.da&&(c[b.h]=c[b.h].toString());c[b.referrer]=""==c[b.u]?"":this.aa(c[b.referrer]);c[b.u]=this.aa(c[b.u]);c[b.Z]=c[b.Z]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.sb())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.cc(c[b.url]),a[b.url]=c[b.url]);return c},
aa:function(a){""!==a&&(a=a||e.qa());return a},sb:function(){return u.ra(b.Ha)},cc:function(a){if(0===a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},p={callbacks:{},S:"SPR",jc:function(a){this.S=a},i:function(a,d,c,h,f){h=h||function(){};f||(f="cb");var l="cb"+g.bc(),k=this;c[f]=this.S+".API.callbacks."+l;f=g.pa();"file://"===f&&(f="http://");c[b.yc]=b.version;c=t.encode(c);var m=e.La(f+
a+d+"?"+c);k.callbacks[l]=function(a){setTimeout(function(){m.parentNode&&m.parentNode.removeChild(m)},0);h(a);try{delete k.callbacks[l]}catch(D){k.callbacks[l]=null}}}},w={hd:!1,bd:!0,w:0,Fa:5E3,uc:12E5,interval:null,reset:function(){e.P=e.N();window.clearInterval(this.interval)},track:function(a){var d=this,c;d.interval=setInterval(function(){e.W&&(d.w+=d.Fa);d.Ga()&&(d.w=0);c=g.O(a);c[b.t]=d.w;c[b.e]=d.Bb()?5E3:0;c[b.Ba]=e.N();0===c[b.b]&&(c[b.b]=b.Ea);e.W&&!d.Ga()&&d.Ac(c)&&0<c[b.e]&&(d.w=0,p.i(b.l,
b.tc,c));d.Eb=e.D.x;d.Fb=e.D.y;d.Db=e.N()},d.Fa)},Bb:function(){return!0!==this.nb?this.nb=!0:this.Eb!==e.D.x||this.Fb!==e.D.y||this.Db!==e.N()?!0:!1},Ga:function(){return this.w>=this.uc},Ac:function(a){return a[b.url]&&a[b.b]}},k=g.$,y={L:[],data:{},response:null,options:null,nd:!1,a:function(a,d){this.reset();this.options=d;this.response=a;var c=this;e.Y(function(){c.height=c.pb();c.I||(c.I=function(){c.fa()});q.current[b.Kb]?c.$b():c.Ma()})},Ma:function(){typeof document.addEventListener!==b.c?
document.addEventListener("scroll",this.I,!1):window.attachEvent("onscroll",this.I);this.fa()},$b:function(){typeof document.removeEventListener!==b.c?document.removeEventListener("scroll",this.I,!1):window.detachEvent("onscroll",this.I)},fa:function(){var a=this.rb()+Math.min(document.documentElement.clientHeight,window.innerHeight||0),b=0;a>=this.height?b=k[3]:b=a/this.height*100;97<=b?this.H(k[3]):b>=k[2]?this.H(k[2]):b>=k[1]?this.H(k[1]):b>=k[0]&&this.H(k[0])},pb:function(){if(q.current[b.ja])var a=
q.current[b.ja];else{a=document.body;var d=document.documentElement;a=Math.max(a.scrollHeight,a.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight)}return a},rb:function(){var a="CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},H:function(a){this.data={};if(!g.contains(k,a))h[b.error](b.va);else if(!g.contains(this.L,a))if(this.kc(a),this.response[b.eb])this.ic();else h[b.info](b.dc)},
kc:function(a){var d;for(d=0;d<k.length;d+=1){var c=k[d];a>=c&&!g.contains(this.L,c)&&(this.L.push(c),this.data[c]=!0,h[b.info](b.Ca+c))}},G:function(){return g.xa({event:"csd",sd:this.data},this.options)},ic:function(){if(!this.response.error){var a=this.G();p.i(b.l,b.na,a)}},reset:function(){this.L=[]}},A={ya:[{name:b.Tb,Oa:b.Ub,Pa:b.Vb,R:b.R}],ac:function(a,b){return{url:b}},qc:function(a,d){return function(c){c={event:b.Ba,url:a.url,cid:a.id,pid:a.pid,sn:a.name,data:c};g.xa(c,d);p.i(b.l,b.na,
c)}},C:function(a,b){for(var c=this.ya,d,e=0;e<c.length;e+=1){d=c[e];var h=g.O(a);h.name=d.name;a[d.name]&&p.i(d.Oa,d.Pa,this.ac(d.name,h.url),this.qc(h,b),d.R)}}},B={track:function(a){var d=this;0===a[b.b]&&(a[b.b]=b.Ea);p.i(b.l,b.ub,a,function(c){y.a(c,a);if(c.error)h[b.error](b.ca+c.error.code+" - "+c.error.message);else c.uid&&d.nc(c.uid),!1!==a[b.pc]&&A.C(c,a)})},nc:function(a){u.ba(b.Ha,a,new Date(2042,5,13))}},x={ad:{},T:{},ga:!1,a:function(){try{e.a();var a=window[b.Xb];u.ra(b.Aa)?this.wa=
!0:this.wa=!1;u.ba(b.Aa,b.Rb,new Date(2042,5,13));this.C(a)}catch(d){e.Y(function(){h.lc(d)})}},C:function(a){if(a){var d;q.current=a;this.T=g.O(q.current);this.T[b.r]=this.wa;(d=this.T[b.Na]&&this.ga)||(a[b.url]=a[b.url]||e.la());if(a[b.url])h.a(a[b.ta]),d&&(a.hasOwnProperty(b.ua)||(a[b.ua]=!0),a[b.Z]=a[b.u]=a[b.referrer]=a.url),a[b.title]||(a[b.title]=e.ka(a[b.url])),a[b.h]||(a[b.h]=e.hb()),a[b.K]||(a[b.K]=e.V(b.Wa,b.Xa)),a[b.B]||(a[b.B]=e.V(b.Ua,b.Ra)),a[b.A]||(a[b.A]=e.V(b.Ta,b.Qa)),w.reset(),
d=v.ea(a),d[b.Wb]||(!1!==a[b.Yb]&&(B.track(d),w.track(d)),!1!==a[b.fb]&&this.lb(d)),this.ga=!0;else h[b.error](b.ca+b.ma)}else h[b.error]("Params not passed to collect")},lb:function(a){a[b.referrer]=a[b.referrer]||e.qa();a[b.u]=v.aa(a[b.u]);a[b.Za]=(new Date).getTime();a=t.encode(a);this.ia&&e.Zb(this.ia);this.ia=e.Ka(b.Da+b.ab+b.bb+"?"+a,b.x)}},r=[b.b,b.Lc,b.Gb,b.h],C={create:function(a,b){return new z(a,b)},a:function(a,b){return this.create(a,b).a()}};return{Reach:{collect:function(a){x.C(a)}},
QS:{decode:t.decode},debug:h,setLogLevel:function(a){h.mc(a)},API:p,collect:function(a){x.C(a)},decode:t.decode,init:function(){x.a()},iframeCollect:function(){},stop:function(){w.reset()},scrollDepthReached:function(a){y.H(a)},video:function(a){return C.a(a,p.S)}}}();window.SPR.init();
