(self.AMP=self.AMP||[]).push({n:"amp-geo",v:"1810152207300",f:(function(AMP,_){
function g(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function h(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var k=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function l(a){var b=Object.create(null);if(!a)return b;for(var c;c=k.exec(a);){var d=h(c[1],c[1]),e=c[2]?h(c[2],c[2]):"";b[d]=e}return b};var m="";
function n(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=!!(self.AMP_CONFIG||{}).test||!1,e=l(c.location.originalHash||c.location.hash),f=l(c.location.search);m||(m=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011810152207300");c=b.AMP_MODE={localDev:!1,development:!("1"!=e.development&&!c.AMP_DEV_MODE),examiner:"2"==e.development,filter:e.filter,geoOverride:e["amp-geo"],minified:!0,lite:void 0!=f.amp_lite,test:d,log:e.log,version:"1810152207300",rtvVersion:m}}return c};var t=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var u=self.log;function v(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function w(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=x(b,"ampdoc").getAmpDoc(a)}return a}function x(a,b){y(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function y(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function z(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function A(a,b){z(a.documentElement,function(){return!!a.body},b)}function B(a){return new Promise(function(b){A(a,b)})}
function C(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function D(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}};var E={"preset-eea":"AT BE BG HR CY CZ DK EE FI FR DE GR HU IS IE IT LV LI LT LU MT NL NO PL PT RO SK SI ES SE GB AX IC EA GF PF TF GI GP GG JE MQ YT NC RE BL MF PM SJ VA WF EZ CH".split(" ")};var F=/amp-iso-country-(\w+)/;function G(a){a=AMP.BaseElement.call(this,a)||this;a.l=0;a.c="unknown";a.h=[];a.j=[];return a}g(G,AMP.BaseElement);G.prototype.buildCallback=function(){var a=this.element.children;a.length&&H(1===a.length&&C(a[0]),'amp-geo can only have one <script type="application/json"> child');var a=a.length?D(a[0].textContent,function(){return H(!1,"amp-geo Unable to parse JSON")}):{},b=I(this,a||{});J.resolve(b)};
function H(a,b){if(!a){J.resolve(null);if(!u.user)throw Error("failed to call initLogConstructor");return u.user.assert(a,b)}return a}
function K(a,b){var c=b.body.className.match(F),d;if(d=c){a:{d=a.getAmpDoc();if(d.nodeType){var e=(d.ownerDocument||d).defaultView;if(e=e!=(e.__AMP_TOP||e)&&y(e,"url")?x(e,"url"):null){d=e;break a}}d=w(d);d=w(d);d=d.isSingleDoc()?d.win:d;d=x(d,"url")}d=!d.isProxyOrigin(b.location)}d?(a.l=1,a.c=c[1]):(a.l=0,a.c="us                          ".trim(),2!==a.c.length&&(a.c="unknown"));if(b=n(a.win).geoOverride)b=a.win,b=!(!b.AMP_CONFIG||!b.AMP_CONFIG.canary);b&&/^\w+$/.test(n(a.win).geoOverride)&&(a.l=
2,a.c=n(a.win).geoOverride.toLowerCase())}function L(a,b){var c=b.ISOCountryGroups,d="<amp-geo> ISOCountryGroups";c&&(H("[object Object]"===t.call(c),d+" must be an object"),a.j=Object.keys(c),a.j.forEach(function(b){H(/^[a-z]+[a-z0-9]*$/i.test(b)&&!/^amp/.test(b),d+"["+b+"] name is invalid");H(Array.isArray(c[b]),d+"["+b+"] must be an array");M(a,c[b])&&a.h.push(b)}))}
function M(a,b){var c=b.reduce(function(a,b){if(/^preset-/.test(b))return H(Array.isArray(E[b]),"<amp-geo> preset "+b+" not found"),a.concat(E[b]);a.push(b);return a},[]).map(function(a){return a.toLowerCase()});return c.includes(a.c)}function N(a){var b=a.body.classList,c=[],d=/^amp-iso-country-|^amp-geo-group-/i;for(a=b.length-1;0<a;a--)d.test(b[a])&&c.push(b[a]);return c}
function I(a,b){var c=a.win.document,d={};return B(c).then(function(){K(a,c);L(a,b);var e=[];switch(a.l){case 2:e=N(c);case 0:d.ISOCountry=a.c;var f=a.h.map(function(a){d[a]=!0;return"amp-geo-group-"+a});a.h.length||f.push("amp-geo-no-group");d.ISOCountryGroups=a.h;f.push("amp-iso-country-"+a.c);a.mutateElement(function(){var a=c.body.classList;e.push("amp-geo-pending");e.forEach(function(b){return a.remove(b)});f.forEach(function(b){return a.add(b)});if(b.AmpBind){var p=c.getElementById("ampGeo");
p&&p.parentNode.removeChild(p);var q=c.createElement("amp-state"),r=c.createElement("script");r.setAttribute("type","application/json");r.textContent=JSON.stringify(d);q.appendChild(r);q.id="ampGeo";c.body.appendChild(q)}},c.body)}return{ISOCountry:a.c,matchedISOCountryGroups:a.h,allISOCountryGroups:a.j,isInCountryGroup:a.isInCountryGroup.bind(a),ISOCountryGroups:a.h}})}
G.prototype.isInCountryGroup=function(a){var b=this,c=a.trim().split(/,\s*/);return c.filter(function(a){return 0<=b.j.indexOf(a)}).length!==c.length?1:0<c.filter(function(a){return 0<=b.h.indexOf(a)}).length?2:3};var J=null;(function(a){J=new v;a.registerElement("amp-geo",G);a.registerServiceForDoc("geo",function(){return J.promise})})(self.AMP);
})});
//# sourceMappingURL=amp-geo-0.1.js.map

