(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"1810152207300",f:(function(AMP,_){
var m,aa=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this);function ba(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function fa(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ga=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ha(a){var b=Object.create(null);if(!a)return b;for(var c;c=ga.exec(a);){var d=fa(c[1],c[1]),e=c[2]?fa(c[2],c[2]):"";b[d]=e}return b};var ia="";
function r(){var a,b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=!!(self.AMP_CONFIG||{}).test||!1,e=ha(c.location.originalHash||c.location.hash),f=ha(c.location.search);ia||(ia=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011810152207300");c=b.AMP_MODE={localDev:!1,development:!("1"!=e.development&&!c.AMP_DEV_MODE),examiner:"2"==e.development,filter:e.filter,geoOverride:e["amp-geo"],minified:!0,lite:void 0!=f.amp_lite,test:d,log:e.log,version:"1810152207300",rtvVersion:ia}}return c}
;var ja=Object.prototype.toString;function ka(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b}function la(a){return"[object Object]"===ja.call(a)};function ma(a){var b=a.message,c=String(Math.random());a.message=c;if(a.message===c)return a.message=b,a;var b=Error(a.message),d;for(d in a)b[d]=a[d];b.stack=a.stack;return b}self.log=self.log||{user:null,dev:null,userForEmbed:null};var na=self.log;function t(){if(!na.user)throw Error("failed to call initLogConstructor");return na.user}function v(){if(na.dev)return na.dev;throw Error("failed to call initLogConstructor");};var oa=Object.prototype.hasOwnProperty;function z(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function A(a){return a||{}}function pa(a,b){if(oa.call(a,b))return a[b]}
function qa(a,b){var c=10,c=void 0===c?10:c,d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.t=b.t;a.s=b.s;a.d=b.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>c?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(oa.call(a.t,b)){var d=a.t[b];if(la(c)&&la(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}};function ra(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function za(a,b,c){if(a.nodeType){var d=Aa((a.ownerDocument||a).defaultView,b);if(d)return d}return!a.nodeType||c?C(a,b):null}function Ba(a,b){var c=D(a);Aa(a,"bind");Ca(a,a,"bind",function(){return b});F(a,"bind")}function Aa(a,b){var c=D(a);return a!=c&&Da(a,b)?F(a,b):null}function L(a,b){a=D(a);return F(a,b)}function Ea(a){var b=M(a),b=N(b);return F(b,"history")}function C(a,b){a=M(a);a=N(a);return F(a,b)}function D(a){return a.__AMP_TOP||a}
function M(a){return a.nodeType?L((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function N(a){a=M(a);return a.isSingleDoc()?a.win:a}function F(a,b){Da(a,b);var c=Fa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ca(a,b,c,d){var e=Fa(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=d,f.context=b,f.resolve&&F(a,c))}
function Ga(a,b){var c=Ha(a,b);if(c)return c;var d=new ra,e=d,f=e.promise,e=e.resolve;Fa(a)[b]={obj:null,promise:f,resolve:e,context:null,ctor:null};return f}function Ha(a,b){var c=Fa(a)[b];if(c){if(c.promise)return c.promise;F(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Fa(a){var b=a.services;b||(b=a.services={});return b}function Da(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function O(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function Ia(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Ja(a,b){Ia(a.documentElement,function(){return!!a.body},b)}function Ka(a){return new Promise(function(b){Ja(a,b)})}function La(a,b){for(var c=0,d;void 0!==(d=a[c]);c++)b(d,c)}
function Ma(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function Na(a){var b=M(a),c=Ha(N(a),"bind");return c?c:b.whenBodyAvailable().then(function(){return Oa(b.win,b.getHeadNode())}).then(function(){var c=b.win;return c.ampExtendedElements&&c.ampExtendedElements["amp-bind"]?Ga(N(a),"bind"):null})}function Pa(a){var b=za(a,"bind");if(b)return Promise.resolve(b);if(a.nodeType){var b=a.ownerDocument.defaultView,c=D(b);return b!==c?Qa(b):Na(a)}return Promise.resolve(null)}
function Oa(a,b){var c;if(b){c=[];b=b.querySelectorAll("script[custom-element]");for(var d=0;d<b.length;d++)c.push(b[d].getAttribute("custom-element"))}else c=[];if(!c.includes("amp-bind"))return Promise.resolve();var e=L(a,"extensions");return e.waitForExtension(a,"amp-bind")}function Qa(a){return Ka(a.document).then(function(){return Oa(a,a.document.head)}).then(function(){return a.ampExtendedElements&&a.ampExtendedElements["amp-bind"]?Ga(a,"bind"):null})};function Ra(a){this.ia=a;this.P=this.V=0;this.L=Object.create(null)}Ra.prototype.has=function(a){return!!this.L[a]};Ra.prototype.get=function(a){var b=this.L[a];if(b)return b.access=++this.P,b.payload};Ra.prototype.put=function(a,b){this.has(a)||this.V++;this.L[a]={payload:b,access:this.P};if(!(this.V<=this.ia)){v().warn("lru-cache","Trimming LRU cache");a=this.L;var c=this.P+1,d,e;for(e in a){var f=a[e].access;f<c&&(c=f,d=e)}void 0!==d&&(delete a[d],this.V--)}};var P=self.AMP_CONFIG||{},Sa={thirdParty:P.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:P.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof P.thirdPartyFrameRegex?new RegExp(P.thirdPartyFrameRegex):P.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:P.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof P.cdnProxyRegex?new RegExp(P.cdnProxyRegex):P.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:P.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:P.localDev||!1};var bb=A({c:!0,v:!0,a:!0,ad:!0}),cb,db,eb=/[?&]amp_js[^&]*/,fb=/[?&]amp_gsa[^&]*/,gb=/[?&]amp_r[^&]*/,hb=/[?&]usqp[^&]*/;
function Q(a){var b;cb||(cb=self.document.createElement("a"),db=self.UrlCache||(self.UrlCache=new Ra(100)));var c=b?null:db,d=cb;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;
e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function ib(a){"string"==typeof a&&(a=Q(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function jb(a,b){var c;c=void 0===c?"source":c;t().assert(null!=a,"%s %s must be available",b,c);var d=a;t().assert(ib(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function kb(a){"string"==typeof a&&(a=Q(a));return Sa.cdnProxyRegex.test(a.origin)}
function lb(a){"string"==typeof a&&(a=Q(a));if(!kb(a))return a.href;var b=a.pathname.split("/"),c=b[1];t().assert(bb[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);t().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(eb,"").replace(fb,"").replace(gb,"").replace(hb,"").replace(/^[?&]/,""))?"?"+c:"":"";return b+c+(a.hash||"")}
function mb(a,b){"string"==typeof b&&(b=Q(b));var c;if("function"==typeof URL)c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=Q(d));c=c.replace(/\\/g,"/");var e=Q(c);c=O(c.toLowerCase(),e.protocol)?e.href:O(c,"//")?d.protocol+c:O(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function nb(a){var b=Q(a),c=ha(b.search);t().assert(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function ob(a,b){if("."==b)return a;var c=b.split(".");for(b=0;b<c.length;b++){var d=c[b];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function pb(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}}
function qb(a,b){var c=10,c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var f=Object.keys(b),g=Object.keys(c);if(f.length!==g.length)return!1;for(e=
0;e<f.length;e++){var h=f[e];a.push({a:b[h],b:c[h],depth:d-1})}continue}}if(b!==c)return!1}return!0};function rb(){var a=sb();return function(b){return setTimeout(b,a())}}function sb(){var a=0;return function(){var b=Math.pow(1.5,a++),c;c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var tb,ub="Webkit webkit Moz moz ms O o".split(" ");function vb(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var wb=!1;function xb(a){if(!wb){wb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c],f;f=d.style;var g=c;if(O(g,"--"))f=g;else{tb||(tb=z());var h=tb[g];if(!h){h=g;if(void 0===f[g]){var n=g.charAt(0).toUpperCase()+g.slice(1);b:{for(var q=0;q<ub.length;q++){var l=ub[q]+n;if(void 0!==f[l]){n=l;break b}}n=""}void 0!==f[n]&&(h=n)}tb[g]=h}f=h}f&&(d.style[f]=e)}}};var R=self.AMPErrors||[];self.AMPErrors=R;function yb(a){yb=rb();return yb(a)}function zb(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var Ab;
function S(a,b){try{var c;if(a)if(void 0!==a.message)a=ma(a),c=!0;else{var d=a;a=Error(zb(d));a.origError=d}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var e=b||a.associatedElement;e&&e.classList&&(e.classList.add("i-amphtml-error"),r().development&&(e.classList.add("i-amphtml-element-error"),e.setAttribute("error-message",a.message)));if(self.console){var f=console.error||console.log;a.messageArray?f.apply(console,a.messageArray):e?f.call(console,a.message,e):f.call(console,a.message)}e&&
e.ma&&e.ma("amp:error",a.message);Bb.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(g){setTimeout(function(){throw g;})}}function Bb(a,b,c,d,e){this&&this.document&&xb(this.document);if(!r().development){var f=!1;try{f=Cb()}catch(h){}if(!(f&&.01<Math.random())){var g=Db(a,b,c,d,e,f);g&&(Eb(this,g),yb(function(){var a=new XMLHttpRequest;a.open("POST",Sa.errorReporting,!0);a.send(JSON.stringify(g))}))}}}
function Eb(a,b){var c=L(a,"ampdoc");if(c.isSingleDoc()){var d=c.getAmpDoc(),e=d.getRootNode().documentElement,f=e.hasAttribute("report-errors-to-viewer");if(f){var g=C(d,"viewer");g.hasCapability("errorReporter")?g.isTrustedViewer().then(function(a){if(!a)return!1;g.sendMessage("error",A({m:b.m,a:b.a,s:b.s,el:b.el,v:b.v,jse:b.jse}));return!0}):Promise.resolve(!1)}else Promise.resolve(!1)}else Promise.resolve(!1)}
function Db(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var n=!(self&&self.window),q=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||n)if(h=!0,.001<q)return;var l=0<=a.indexOf("\u200b\u200b\u200b");if(!(l&&.1<q)){g=Object.create(null);g.v=r().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=l?"1":"0";g.ex=h?"1":"0";g.dw=n?"1":"0";var p="1p";self.context&&
self.context.location?(g["3p"]="1",p="3p"):r().runtime&&(p=r().runtime);g.rt=p;"inabox"===p&&(g.adid=r().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var k=self.AMP.viewer.getResolvedViewerUrl(),
E=self.AMP.viewer.maybeGetMessagingOrigin();k&&(g.rvu=k);E&&(g.mso=E)}Ab||(Ab=Fb());g.jse=Ab;var B=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var u in f)B.push(u+"="+(f[u]?"1":"0"));g.exps=B.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),l||e.ignoreStack||!e.stack||(g.s=e.stack),e.message+=" _reported_"):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document.referrer;g.ae=R.join(",");g.fr=self.location.originalHash||self.location.hash;b=
a;25<=R.length&&R.splice(0,R.length-25+1);R.push(b);return g}}}function Cb(){for(var a=self.document.querySelectorAll("script[src]"),b=0;b<a.length;b++)if(!kb(a[b].src.toLowerCase()))return!0;return!1}
function Fb(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(e){var c=e.stack;if(O(c,"t@"))return"Safari";if(-1<c.indexOf(".prototype.t@"))return"Firefox";var d=c.split("\n").pop();if(/\bat .* \(/i.test(d))return"IE";if(O(c,"Error: message"))return"Chrome"}return"unknown"};function Gb(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var h=f;f=null;b.apply(null,h)}}var d=0,e=0,f=null;return function(b){for(var g=[],n=0;n<arguments.length;++n)g[n-0]=arguments[n];e=a.Date.now();f=g;d||(d=a.setTimeout(c,5E3))}};function Hb(a,b){for(var c=0,d=0;d<a.length;d++){var e=a[d];b(e,d,a)||(c<d&&(a[c]=e),c++)}c<a.length&&(a.length=c)}function Ib(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function Jb(){this.F=z();this.j=null}m=Jb.prototype;m.get=function(a){return this.F[a]||null};m.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new ra,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=z());this.j[a]=b}return b.promise};
m.signal=function(a,b){if(null==this.F[a]){var c=b||Date.now();this.F[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};m.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};m.reset=function(a){this.F[a]&&delete this.F[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function T(){this.o=[]}T.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};T.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.o.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.o.length)break;if(this.o[d].priority<c)e=d+1;else if(0<d&&this.o[d-1].priority>=c)f=d-1;else break}this.o.splice(d,0,{item:a,priority:b})};T.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
T.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};aa.Object.defineProperties(T.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});function Kb(a){return AMP.BaseElement.apply(this,arguments)||this}ba(Kb,AMP.BaseElement);m=Kb.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};m.renderOutsideViewport=function(){return!0};m.H=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function Lb(a,b,c){var d,e=void 0,e=void 0===e?".":e;c=void 0===c?0:c;d=void 0===d?!1:d;jb(b.getAttribute("src"),b);var f=L(a.win,"batched-xhr");return Mb(a,b,c,d).then(function(a){return f.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");return ob(a,e||".")})}
function Mb(a,b,c,d){var e=b.getAttribute("src"),f=za(a,"url-replace",!0);return(1<=c?f.expandUrlAsync(e):Promise.resolve(e)).then(function(a){if(1==c){var e=f.collectUnwhitelistedVarsSync(b);if(0<e.length)throw t().createError("URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. "+('Please add data-amp-replace="'+e.join(" ")+'" to the ')+("<"+b.tagName+"> element. See https://bit.ly/amp-var-subs."));}var g={};b.hasAttribute("credentials")?g.credentials=
b.getAttribute("credentials"):g.requireAmpResponseSourceOrigin=!1;d&&(g.cache="reload");return{xhrUrl:a,fetchOpt:g}})};function Nb(a){return AMP.BaseElement.apply(this,arguments)||this}ba(Nb,AMP.BaseElement);m=Nb.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};m.activate=function(){var a=this.H();this.user().error(a,'Please use AMP.setState() action explicitly, e.g. on="submit-success:AMP.setState({myAmpState: event.response})"')};
m.buildCallback=function(){var a=this;vb(this.element);this.element.setAttribute("aria-hidden","true");C(this.getAmpDoc(),"viewer").whenFirstVisible().then(function(){return a.U()})};m.mutatedAttributesCallback=function(a){if(C(this.getAmpDoc(),"viewer").hasBeenVisible())void 0!==a.src&&Wb(this,!1);else{var b=this.H();v().error(b,"Viewer must be visible before mutation.")}};m.renderOutsideViewport=function(){return!0};
m.U=function(){var a=this;this.element.hasAttribute("overridable")&&Pa(this.element).then(function(b){b.makeStateKeyOverridable(a.element.getAttribute("id"))});0<this.element.children.length&&Xb(this);this.element.hasAttribute("src")&&Wb(this,!0)};
function Xb(a){var b=a.H(),c=a.element.children;if(1!=c.length)a.user().error(b,"Should contain exactly one <script> child.");else{var d=c[0];Ma(d)?(c=pb(d.textContent,function(c){a.user().error(b,"Failed to parse state. Is it valid JSON?",c)}),Yb(a,c,!0)):a.user().error(b,'State should be in a <script> tag with type="application/json".')}}function Zb(a,b,c){var d=b.getAttribute("src"),e=1;if(c||Q(lb(d)).origin==Q(lb(a.win.location)).origin)e=2;return Lb(a,b,e)}
function Wb(a,b){var c=a.getAmpDoc();Zb(c,a.element,b).then(function(c){Yb(a,c,b)})}function Yb(a,b,c){if(void 0!==b&&null!==b){var d=t().assert(a.element.id,"<amp-state> must have an id."),e=z();e[d]=b;Pa(a.element).then(function(a){a.setState(e,c,!c)})}}m.H=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var $b=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function ac(a){for(var b=[],c;c=$b.exec(a);){var d=c[1],e=void 0,f;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new bc(b)}
function bc(a){t().assert(0<a.length,"Srcset must have at least one source");this.J=a;for(var b=!1,c=!1,d=0;d<a.length;d++)var e=a[d],b=b||!!e.width,c=c||!!e.dpr;t().assert(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?cc:dc);this.ga=b}
bc.prototype.select=function(a,b){if(this.ga){b*=a;a=this.J;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}}else for(a=this.J,c=0,d=Infinity,e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c;return this.J[b].url};bc.prototype.getUrls=function(){return this.J.map(function(a){return a.url})};
bc.prototype.stringify=function(a){for(var b=[],c=this.J,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.ga?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function cc(a,b){t().assert(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function dc(a,b){t().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var ec={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},fc={width:null,height:null},gc={"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},
"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,
viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,
width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SELECT:{autofocus:null,disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,
spellcheck:null,wrap:null}},hc={src:!0,srcset:!0,href:!0,"xlink:href":!0};function ic(){}ic.prototype.canBind=function(a,b){return void 0!==jc(a,b)};
ic.prototype.isResultValid=function(a,b,c){var d=jc(a,b);d&&d.alternativeName&&(d=jc(a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&pa(hc,b)){var e;if("srcset"===b){var f;try{f=ac(c)}catch(q){return t().error("amp-bind","Failed to parse srcset: ",q),!1}e=f.getUrls()}else e=[c];for(a=0;a<e.length;a++){a:{var g=e[a];if((b=d.allowedProtocols)&&g&&(g=/^([^:\/?#.]+):[\s\S]*$/.exec(g),null!==g&&!oa.call(b,g[1].toLowerCase().trim()))){b=!1;break a}b=!0}if(!b)return!1}}var h=d.blacklistedValueRegex;
if(c&&h){var n=new RegExp(h,"i");if(n.test(c))return!1}return!0};function jc(a,b){if(O(b,"aria-"))return null;var c=pa(ec,b);if(void 0!==c)return c;var d=pa(fc,b);if(O(a,"AMP-")&&void 0!==d)return d;var e=pa(gc,a);if(e)return e[b]};var kc=/nochunking=1/.test(self.location.hash),lc=Promise.resolve();function mc(a,b){if(kc)lc.then(b);else{var c=nc,d=M(a),e=N(d);Ca(e,d,"chunk",c);C(a,"chunk").run(b,10)}}function U(a){this.state="not_run";this.S=a}function oc(a,b){if("run"!=a.state){a.state="run";try{a.S(b)}catch(c){throw a.aa(c),c;}}}U.prototype.H=function(){return this.S.displayName||this.S.name};U.prototype.aa=function(){};U.prototype.$=function(){return!1};U.prototype.fa=function(){return!0};
function pc(a,b,c){U.call(this,a);var d=this;this.h=b;this.B=null;c.then(function(a){d.B=a;d.B.isVisible()&&oc(d,null);d.B.onVisibilityChanged(function(){d.B.isVisible()&&oc(d,null)})})}ba(pc,U);pc.prototype.aa=function(){xb(self.document)};pc.prototype.$=function(){return this.B?this.B.isVisible():this.h.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.h.location.hash)};pc.prototype.fa=function(){return!!this.B};
function nc(a){var b=this;this.h=a.win;this.K=new T;this.X=this.Y.bind(this);this.sa=Ga(N(a),"viewer");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.Y(null)})}nc.prototype.run=function(a,b){var c=new U(a);qc(this,c,b)};nc.prototype.runForStartup=function(a){a=new pc(a,this.h,this.sa);qc(this,a,Number.POSITIVE_INFINITY)};function qc(a,b,c){a.K.enqueue(b,c);lc.then(function(){rc(a)})}
function sc(a,b){for(var c=a.K.peek();c&&"not_run"!==c.state;)a.K.dequeue(),c=a.K.peek();c&&b&&a.K.dequeue();return c}nc.prototype.Y=function(a){var b=this,c=sc(this,!0);if(!c)return!1;oc(c,a);lc.then(function(){rc(b)});return!0};function tc(a){lc.then(function(){a.X(null)})}function rc(a){var b=sc(a);b&&(b.$()?tc(a):b.fa()&&a.h.requestIdleCallback?uc(a.h,a.X):a.h.postMessage("amp-macro-task","*"))}
function uc(a,b){var c=15,d=2E3;function e(g){if(g.timeRemaining()<c){var h=d-(Date.now()-f);0>=h||g.didTimeout?b(g):a.requestIdleCallback(e,{timeout:h})}else b(g)}var f=Date.now();a.requestIdleCallback(e,{timeout:d})};function vc(a,b,c){var d="ww";b?(b=a.protocol+"//"+a.host,"about:"==a.protocol&&(b=""),a=b+"/dist"):a=Sa.cdn;return c?a+"/rtv/"+r().rtvVersion+"/"+d+".js":a+"/"+d+".js"};function wc(a){var b=this;this.h=a;this.ta=L(a,"xhr");var c=a.location,d=!1,e=!d,f=vc(c,d,e);this.W=null;this.Z=this.ta.fetchText(f,{ampCors:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c+"\n//# sourceurl="+f],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.W=new a.Worker(d);b.W.onmessage=b.pa.bind(b)});this.N={};this.ja=0;this.ha=[a]}
function xc(a,b,c,d){return a.Z.then(function(){return new Promise(function(e,f){var g=a.ja++;a.N[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.ha.indexOf(e);var h=0<=f?f:a.ha.push(e)-1;a.W.postMessage({method:b,args:c,scope:h,id:g})})})}wc.prototype.pa=function(a){var b=a.data;a=b.method;var c=b.returnValue,b=b.id,d=this.N[b];d?(d.resolve(c),delete this.N[b]):v().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};wc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.N).length};
wc.prototype.ua=function(){return this.Z};var yc="a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" "),
zc="svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform audio canvas circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan video view vkern".split(" "),Ac="feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" "),
Bc="math menclose merror mfenced mfrac mglyph mi mlabeledtr mmuliscripts mn mo mover mpadded mphantom mroot mrow ms mpspace msqrt mystyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" "),Cc=["#text"],Dc="accept action align alt autocomplete background bgcolor border cellpadding cellspacing checked cite class clear color cols colspan coords crossorigin datetime default dir disabled download enctype face for headers height hidden high href hreflang id integrity ismap label lang list loop low max maxlength media method min multiple name noshade novalidate nowrap open optimum pattern placeholder poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title type usemap valign value width xmlns".split(" "),
Ec="accent-height accumulate additivive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" "),
Fc="accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" "),
Gc=["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"];function Y(a,b){for(var c=b.length;c--;)"string"===typeof b[c]&&(b[c]=b[c].toLowerCase()),a[b[c]]=!0;return a}function Hc(a){var b={},c=void 0;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c]);return b}
var Ic=/\{\{[\s\S]*|[\s\S]*\}\}/gm,Jc=/<%[\s\S]*|[\s\S]*%>/gm,Kc=/^data-[\-\w.\u00B7-\uFFFF]/,Lc=/^aria-[\-\w]+$/,Mc=/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,Nc=/^(?:\w+script|data):/i,Oc=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g,Pc="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};
function Z(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}
function Qc(){function a(a){var c,e,f,g;d("beforeSanitizeAttributes",a,null);var G=a.attributes;if(G){var h={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:w};for(g=G.length;g--;){var l=c=G[g],q=l.name,k=l.namespaceURI;c=c.value.trim();e=q.toLowerCase();h.attrName=e;h.attrValue=c;h.keepAttr=!0;d("uponSanitizeAttribute",a,h);c=h.attrValue;if("name"===e&&"IMG"===a.nodeName&&G.id)f=G.id,G=Array.prototype.slice.apply(G),n("id",a),n(q,a),G.indexOf(f)>g&&a.setAttribute("id",f.value);else if("INPUT"!==
a.nodeName||"type"!==e||"file"!==c||!w[e]&&Ta[e])"id"===q&&a.setAttribute(q,""),n(q,a);else continue;if(h.keepAttr&&b(a.nodeName.toLowerCase(),e,c))try{k?a.setAttributeNS(k,q,c):a.setAttribute(q,c),p.removed.pop()}catch(Bd){}}d("afterSanitizeAttributes",a,null)}}function b(a,b,c){if(Ob&&("id"===b||"name"===b)&&(c in y||c in fd))return!1;ta&&(c=c.replace(Ic," "),c=c.replace(Jc," "));if(!Ua||!Kc.test(b))if(!Pb||!Lc.test(b))if(!w[b]||Ta[b]||!(Qb[b]||Va.test(c.replace(Oc,""))||("src"===b||"xlink:href"===
b)&&"script"!==a&&0===c.indexOf("data:")&&gd[a]||Rb&&!Nc.test(c.replace(Oc,"")))&&c)return!1;return!0}function c(a){var b;d("beforeSanitizeElements",a,null);if(f(a))return q(a),!0;b=a.nodeName.toLowerCase();d("uponSanitizeElement",a,{tagName:b,allowedTags:x});if(!x[b]||Wa[b]){if(Xa&&!hd[b]&&"function"===typeof a.insertAdjacentHTML)try{a.insertAdjacentHTML("AfterEnd",a.innerHTML)}catch(ed){}q(a);return!0}!Sb||a.firstElementChild||a.content&&a.content.firstElementChild||!/</g.test(a.textContent)||(p.removed.push({element:a.cloneNode()}),
a.innerHTML=a.innerHTML?a.innerHTML.replace(/</g,"&lt;"):a.textContent.replace(/</g,"&lt;"));ta&&3===a.nodeType&&(b=a.textContent,b=b.replace(Ic," "),b=b.replace(Jc," "),a.textContent!==b&&(p.removed.push({element:a.cloneNode()}),a.textContent=b));d("afterSanitizeElements",a,null);return!1}function d(a,b,c){H[a]&&H[a].forEach(function(a){a.call(p,b,c,ua)})}function e(a){return"object"===("undefined"===typeof V?"undefined":Pc(V))?a instanceof V:a&&"object"===("undefined"===typeof a?"undefined":Pc(a))&&
"number"===typeof a.nodeType&&"string"===typeof a.nodeName}function f(a){return a instanceof va||a instanceof wa?!1:"string"===typeof a.nodeName&&"string"===typeof a.textContent&&"function"===typeof a.removeChild&&a.attributes instanceof xa&&"function"===typeof a.removeAttribute&&"function"===typeof a.setAttribute?!1:!0}function g(a){return id.call(a.ownerDocument||a,a,J.SHOW_ELEMENT|J.SHOW_COMMENT|J.SHOW_TEXT,function(){return J.FILTER_ACCEPT},!1)}function h(a){var b=void 0;Ya&&(a="<remove></remove>"+
a);if(B)try{b=(new ca).parseFromString(a,"text/html")}catch(Ad){}u&&Y(Wa,["title"]);if(!b||!b.documentElement){var c=b=Za.createHTMLDocument(""),d=c.body;d.parentNode.removeChild(d.parentNode.firstElementChild);d.outerHTML=a}return jd.call(b,da?"html":"body")[0]}function n(a,b){try{p.removed.push({attribute:b.getAttributeNode(a),from:b})}catch(ed){p.removed.push({attribute:null,from:b})}b.removeAttribute(a)}function q(a){p.removed.push({element:a});try{a.parentNode.removeChild(a)}catch(sa){a.outerHTML=
""}}function l(a){"object"!==("undefined"===typeof a?"undefined":Pc(a))&&(a={});x="ALLOWED_TAGS"in a?Y({},a.ALLOWED_TAGS):Tb;w="ALLOWED_ATTR"in a?Y({},a.ALLOWED_ATTR):Ub;Wa="FORBID_TAGS"in a?Y({},a.FORBID_TAGS):{};Ta="FORBID_ATTR"in a?Y({},a.FORBID_ATTR):{};W="USE_PROFILES"in a?a.USE_PROFILES:!1;Pb=!1!==a.ALLOW_ARIA_ATTR;Ua=!1!==a.ALLOW_DATA_ATTR;Rb=a.ALLOW_UNKNOWN_PROTOCOLS||!1;Sb=a.SAFE_FOR_JQUERY||!1;ta=a.SAFE_FOR_TEMPLATES||!1;da=a.WHOLE_DOCUMENT||!1;ea=a.RETURN_DOM||!1;$a=a.RETURN_DOM_FRAGMENT||
!1;Vb=a.RETURN_DOM_IMPORT||!1;Ya=a.FORCE_BODY||!1;Ob=!1!==a.SANITIZE_DOM;Xa=!1!==a.KEEP_CONTENT;ya=a.IN_PLACE||!1;Va=a.ALLOWED_URI_REGEXP||Va;ta&&(Ua=!1);$a&&(ea=!0);W&&(x=Y({},[].concat(Z(Cc))),w=[],!0===W.html&&(Y(x,yc),Y(w,Dc)),!0===W.svg&&(Y(x,zc),Y(w,Ec),Y(w,Gc)),!0===W.svgFilters&&(Y(x,Ac),Y(w,Ec),Y(w,Gc)),!0===W.mathMl&&(Y(x,Bc),Y(w,Fc),Y(w,Gc)));a.ADD_TAGS&&(x===Tb&&(x=Hc(x)),Y(x,a.ADD_TAGS));a.ADD_ATTR&&(w===Ub&&(w=Hc(w)),Y(w,a.ADD_ATTR));a.ADD_URI_SAFE_ATTR&&Y(Qb,a.ADD_URI_SAFE_ATTR);Xa&&
(x["#text"]=!0);da&&Y(x,["html","head","body"]);x.table&&Y(x,["tbody"]);Object&&"freeze"in Object&&Object.freeze(a);ua=a}function p(a){return Qc(a)}var k=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;p.version="1.0.8";p.removed=[];if(!k||!k.document||9!==k.document.nodeType)return p.isSupported=!1,p;var E=k.document,B=!1,u=!1,y=k.document,K=k.DocumentFragment,V=k.Node,J=k.NodeFilter,I=k.NamedNodeMap,xa=void 0===I?k.NamedNodeMap||k.MozNamedAttrMap:I,
va=k.Text,wa=k.Comment,ca=k.DOMParser;"function"===typeof k.HTMLTemplateElement&&(I=y.createElement("template"),I.content&&I.content.ownerDocument&&(y=I.content.ownerDocument));var X=y,Za=X.implementation,id=X.createNodeIterator,jd=X.getElementsByTagName,kd=X.createDocumentFragment,ld=E.importNode,H={};p.isSupported=Za&&"undefined"!==typeof Za.createHTMLDocument&&9!==y.documentMode;var Va=Mc,x=null,Tb=Y({},[].concat(Z(yc),Z(zc),Z(Ac),Z(Bc),Z(Cc))),w=null,Ub=Y({},[].concat(Z(Dc),Z(Ec),Z(Fc),Z(Gc))),
Wa=null,Ta=null,Pb=!0,Ua=!0,Rb=!1,Sb=!1,ta=!1,da=!1,ab=!1,Ya=!1,ea=!1,$a=!1,Vb=!1,Ob=!0,Xa=!0,ya=!1,W={},hd=Y({},"audio head math script style template svg video".split(" ")),gd=Y({},["audio","video","img","source","image"]),Qb=Y({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),ua=null,fd=y.createElement("form");p.isSupported&&(function(){try{h('<svg><p><style><img src="</style><img src=x onerror=alert(1)//">').querySelector("svg img")&&(B=!0)}catch(G){}}(),
function(){try{h("<x/><title>&lt;/title&gt;&lt;img&gt;").querySelector("title").textContent.match(/<\/title/)&&(u=!0)}catch(G){}}());var md=function sa(b){var e=void 0,f=g(b);for(d("beforeSanitizeShadowDOM",b,null);e=f.nextNode();)d("uponSanitizeShadowNode",e,null),c(e)||(e.content instanceof K&&sa(e.content),a(e));d("afterSanitizeShadowDOM",b,null)};p.sanitize=function(b,d){var f=void 0,n=void 0,B=void 0,u=void 0;b||(b="\x3c!--\x3e");if("string"!==typeof b&&!e(b)){if("function"!==typeof b.toString)throw new TypeError("toString is not a function");
b=b.toString();if("string"!==typeof b)throw new TypeError("dirty is not a string, aborting");}if(!p.isSupported){if("object"===Pc(k.toStaticHTML)||"function"===typeof k.toStaticHTML){if("string"===typeof b)return k.toStaticHTML(b);if(e(b))return k.toStaticHTML(b.outerHTML)}return b}ab||l(d);p.removed=[];if(!ya)if(b instanceof V)f=h("\x3c!--\x3e"),n=f.ownerDocument.importNode(b,!0),1===n.nodeType&&"BODY"===n.nodeName?f=n:f.appendChild(n);else{if(!ea&&!da&&-1===b.indexOf("<"))return b;f=h(b);if(!f)return ea?
null:""}f&&Ya&&q(f.firstChild);for(var sa=g(ya?b:f);d=sa.nextNode();)3===d.nodeType&&d===B||c(d)||(d.content instanceof K&&md(d.content),a(d),B=d);if(ya)return b;if(ea){if($a)for(u=kd.call(f.ownerDocument);f.firstChild;)u.appendChild(f.firstChild);else u=f;Vb&&(u=ld.call(E,u,!0));return u}return da?f.outerHTML:f.innerHTML};p.setConfig=function(a){l(a);ab=!0};p.clearConfig=function(){ua=null;ab=!1};p.isValidAttribute=function(a,c,d){ua||l({});return b(a.toLowerCase(),c.toLowerCase(),d)};p.addHook=
function(a,b){"function"===typeof b&&(H[a]=H[a]||[],H[a].push(b))};p.removeHook=function(a){H[a]&&H[a].pop()};p.removeHooks=function(a){H[a]&&(H[a]=[])};p.removeAllHooks=function(){H={}};return p}Qc();A({input:{type:/(?:image|button)/i}});var Rc="form formaction formmethod formtarget formnovalidate formenctype".split(" ");A({input:Rc,textarea:Rc,select:Rc});function Sc(a,b,c){var d=self.location;nb(c);var e=kb(d),f=Q(lb(d));if("href"==b&&!O(c,"#"))return mb(c,f);if("src"==b)return"amp-img"==a?Tc(c,f,e):mb(c,f);if("srcset"==b){var g;try{g=ac(c)}catch(h){return t().error("purifier","Failed to parse srcset: ",h),c}return g.stringify(function(a){return Tc(a,f,e)})}return c}
function Tc(a,b,c){a=Q(mb(a,b));return"data:"==a.protocol||kb(a)||!c?a.href:Sa.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var Uc=/^(i?-)?amp(html)?-/,Vc=z({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state"],"AMP-SELECTOR":["selected"]});
function Wc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.I=b||a.win;this.R=[];this.na=Gb(this.h,function(){c.R.length=0});this.C=[];this.D=z();this.T=Ea(a);this.ba=[];this.G=1E3;this.da=C(a,"resources");this.w=z();this.qa=L(this.h,"timer");this.ra=new ic;this.B=C(this.ampdoc,"viewer");this.B.onMessageRespond("premutate",this.oa.bind(this));this.M=this.B.whenFirstVisible().then(function(){if(b){var c=b.document;return Ka(c).then(function(){return c})}return a.whenBodyAvailable().then(function(){return a.getRootNode()})}).then(function(a){return c.U(a)});
this.O=null;this.ea=new Jb;var d=self.AMP;d.printState=d.printState||this.la.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.ka.bind(this)}m=Wc.prototype;m.adoptEmbedWindow=function(a){Ba(a,new Wc(this.ampdoc,a))};m.signals=function(){return this.ea};
m.setState=function(a,b,c){var d=this;try{qa(this.w,a)}catch(e){t().error("amp-bind","Failed to merge result from AMP.setState().",e)}v().info("amp-bind","state:",this.w);return b?Promise.resolve():this.O=this.M.then(function(){return Xc(d)}).then(function(a){return Yc(d,a,c)})};
m.invoke=function(a){var b=a,c=b.args,d=b.event,e=b.method,f=b.sequenceId,g=b.tagOrTarget;if(this.R.includes(f))return t().error("amp-bind","One state action allowed per event."),Promise.resolve();this.R.push(f);this.na();if(b=c.__AMP_OBJECT_STRING__)switch(this.G=Math.min(2E3,Math.max(1E3,this.G+500)),this.ea.signal("FIRST_MUTATE"),c={},d&&d.detail&&(c.event=d.detail),e){case "setState":return this.setStateWithExpression(b,c);case "pushState":return this.pushStateWithExpression(b,c);default:return Promise.reject(v().createError("Unrecognized method: "+
('"'+g+"."+e+'"')))}else t().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return Promise.resolve()};m.setStateWithExpression=function(a,b){var c=this;v().info("amp-bind","setState:",'"'+a+'"');return this.O=Zc(this,a,b).then(function(a){return c.setState(a)}).then(function(){c.T.replace({data:A({"amp-bind":c.w}),title:c.I.document.title})})};
m.pushStateWithExpression=function(a,b){var c=this;v().info("amp-bind","pushState:",a);return Zc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=z();Object.keys(a).forEach(function(a){var b;a:{var e=c.w[a];if(void 0!==e)try{b=JSON.parse(JSON.stringify(e));break a}catch(q){v().error("amp-bind","Failed to copy JSON ("+e+") with error: "+q)}b=null}d[a]=b});return c.setState(a).then(function(){c.T.push(b,{data:A({"amp-bind":c.w}),title:c.I.document.title})})})};
m.scanAndApply=function(a,b,c){function d(a){$c(e,b).then(function(b){v().info("amp-bind","\u2937","\u0394:",a-b,", \u2211:",e.numberOfBindings())});return Promise.resolve()}c=void 0===c?2E3:c;var e=this;v().info("amp-bind","rescan:",a,b);if(this.numberOfBindings()>this.G)return ad(this),d(0);var f=[],g=a.slice();a.forEach(function(a){Array.prototype.push.apply(g,a.querySelectorAll("[i-amphtml-binding]"))});g.forEach(function(a){bd(e,a,Number.POSITIVE_INFINITY,f)});var h=f.length;if(0===h)return d(0);
var n=cd(this,f).then(function(){return Xc(e).then(function(b){return dd(e,b,a)})}).then(function(){d(h)});return this.qa.timeoutPromise(c,n,"Timed out waiting for amp-bind to process rendered template.")};m.getStateValue=function(a){a=ob(this.w,a);return la(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
m.U=function(a){var b=this;v().info("amp-bind","init");return Promise.all([nd(this),od(this,[a])]).then(function(c){v().info("amp-bind","\u2937","\u0394:",c);a.addEventListener("amp:dom-update",function(a){return pd(b,a)});if(r().development)return Xc(b).then(function(a){return qd(b,a)})}).then(function(){b.B.sendMessage("bindReady",void 0)})};m.numberOfBindings=function(){return this.C.reduce(function(a,b){return a+b.boundProperties.length},0)};m.xa=function(a){this.G=a};m.va=function(){return this.T};
m.oa=function(a){var b=this,c=[];return this.M.then(function(){Object.keys(a.state).forEach(function(d){b.ba.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&t().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};m.makeStateKeyOverridable=function(a){this.ba.push(a)};
function nd(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];La(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):rd(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){sd(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function od(a,b){var c=b.map(function(b){var c=a.G-a.numberOfBindings();return td(a,b,c).then(function(b){var c=b.bindings,d=b.limitExceeded;d&&ad(a);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?cd(a,b):0})}function ad(a){v().expectedError("amp-bind","Maximum number of bindings reached "+("("+a.G+"). Additional elements with ")+"bindings will be ignored.")}
function cd(a,b){return rd(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.D[b];0<d.length&&sd(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function $c(a,b){Hb(a.C,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];Hb(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?rd(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function td(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();var d=c-e.length;bd(a,b,d,e)&&(g=!0);return!f.nextNode()||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var l=!1;if(f&&!f.didTimeout)for(;1<f.timeRemaining()&&!l;)l=d();else{var h=250;for(f=0;f<h&&!l;f++)l=d()}l?b({bindings:e,limitExceeded:g}):mc(a.ampdoc,c)}mc(a.ampdoc,
c)})}function bd(a,b,c,d){var e=!1,f=ud(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.C.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c,f=e.expressionString;d.push({tagName:g,property:e.property,expressionString:f});a.D[f]||(a.D[f]=[]);a.D[f].push(b)});return e}
function ud(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){var g;a:{var h=void 0,n=a,q=d[e];g=b;var l=g.tagName,p=q.name;if(2<p.length&&"["===p[0]&&"]"===p[p.length-1])h=p.substr(1,p.length-2);else if(O(p,"data-amp-bind-")&&(h=p.substr(14),g.hasAttribute("["+h+"]"))){g=null;break a}if(h){if(n.ra.canBind(l,h)){g={property:h,expressionString:q.value};break a}h=t().createError("amp-bind: Binding to ["+h+"] on <"+l+"> is not allowed.");S(h,g)}g=null}g&&c.push(g)}return c}
function Zc(a,b,c){return a.M.then(function(){Object.assign(c,a.w);return rd(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw sd(a,"amp-bind: Expression eval failed.");v().info("amp-bind","\u2937",b);return b})}
function Xc(a){var b=rd(a,"bind.evaluateBindings",[a.w]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.D[b];if(0<c.length){var d=e[b],f=t().createError('amp-bind: Expression evaluation error in "'+b+'". '+d.message);f.stack=d.stack;S(f,c[0])}});v().info("amp-bind","bindings:",c);return c})}
function qd(a,b){var c,d;c=void 0===c?null:c;d=void 0===d?!0:d;var e={};a.C.forEach(function(a){var f=a.element;a=a.boundProperties;c&&!vd(c,f)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var g=a.property,l=Vc[f.tagName];if(l&&l.includes(g))c=null;else{switch(g){case "text":g=f.textContent;c=String(c);l=g.trim()===c.trim();break;case "class":g=[];for(l=0;l<f.classList.length;l++){var h=f.classList[l];Uc.test(h)||g.push(h)}h=[];Array.isArray(c)?h=c:"string"===typeof c?(l=c.trim(),
0<l.length&&(h=l.split(" "))):(l=t().createError('amp-bind: "'+c+'" is not a valid result for [class].'),S(l,f));b:{var l=g,k=h;if(l.length!==k.length)l=!1;else{for(var h=(Array.isArray(l)?l:ka(l)).sort(),k=(Array.isArray(k)?k:ka(k)).sort(),E=0;E<l.length;E++)if(h[E]!==k[E]){l=!1;break b}l=!0}}break;default:g=f.getAttribute(g),l=!0===c?""===g:!1===c?null===g:g===c}c=l?null:{expected:c,actual:g}}var B=c;if(B){c=f.tagName;g=a.property;a=a.expressionString;var l=B,h=l.expected,u=l.actual;e[c+"["+g+"]"+
h+":"+u]=!0;d&&t().warn("amp-bind","Default value ("+u+") does not match first "+("result ("+h+") for <"+c+" ["+g+']="')+(a+'">. We recommend writing expressions with ')+"matching default values, but this can be safely ignored if intentional.")}}})});return Object.keys(e)}function vd(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function wd(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||qb(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function Yc(a,b,c){var d=a.C.map(function(d){return c&&"AMP-STATE"==d.element.tagName?Promise.resolve():xd(a,b,d)});return Promise.all(d).then(function(){v().info("amp-bind","updated:",d.length,"elements")})}
function dd(a,b,c){var d=[];a.C.forEach(function(e){c.forEach(function(c){c.contains(e.element)&&d.push(xd(a,b,e))})});return Promise.all(d).then(function(){v().info("amp-bind","updated:",d.length,"elements")})}
function xd(a,b,c){var d=c.element,e=wd(c.boundProperties,b);return 0===e.length?Promise.resolve():a.da.mutateElement(d,function(){var b=z(),c,h;e.forEach(function(e){var f=e,g=f.boundProperty,f=f.newValue,k;a:{k=g.property;var n=d.tagName;switch(k){case "text":d.textContent=String(f);"TITLE"===n&&d.parentNode===a.I.document.head&&(a.I.document.title=String(f));"TEXTAREA"==n&&(d.value=String(f));break;case "class":k=[];for(var q=0;q<d.classList.length;q++){var u=d.classList[q];Uc.test(u)&&k.push(u)}Array.isArray(f)||
"string"===typeof f?d.setAttribute("class",k.concat(f).join(" ")):null===f?d.setAttribute("class",k.join(" ")):(k=t().createError('amp-bind: "'+f+'" is not a valid result for [class].'),S(k,d));break;default:var n="INPUT"==n&&k in d,y=d.getAttribute(k),K=!1;if("boolean"===typeof f)n&&d[k]!==f&&(d[k]=f,K=!0),f&&""!==y?(d.setAttribute(k,""),K=!0):f||null===y||(d.removeAttribute(k),K=!0);else if(f!==y)b:{y=String(f);try{var q=d.tagName.toLowerCase(),u=k.toLowerCase(),V=q.toLowerCase(),J=u.toLowerCase(),
I="src"==J||"href"==J||"srcset"==J?Sc(V,J,y):y;if(kb(self.location)&&"a"===q&&"href"===u){var xa=d.getAttribute(u),va="#"===I[0],wa=xa&&"#"===xa[0];va&&!wa?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):wa&&!va&&d.setAttribute("target",d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}n&&(d[u]=I);d.setAttribute(u,I);K=!0;break b}catch(X){q=t().createError('amp-bind: "'+y+'" is not a '+("valid result for ["+k+"]"),X),S(q,d)}K=!1}if(K){k=
{name:k,value:f};break a}}k=null}var ca=k;ca&&(b[ca.name]=ca.value,g=g.property,"width"==g?c="number"===typeof f&&isFinite(f)?Number(f):c:"height"==g&&(h="number"===typeof f&&isFinite(f)?Number(f):h))});void 0===c&&void 0===h||a.da.changeSize(d,h,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(q){var n=t().createError("amp-bind: Applying expression "+("results ("+JSON.stringify(b)+") failed with error"),q);S(n,d)}})}
function pd(a,b){b=b.target;var c=b.parentNode;c&&"AMP-LIST"==c.tagName||(v().info("amp-bind","dom_update:",b),yd(a,[b],[b]).then(function(){}))}function yd(a,b,c){var d=0;return $c(a,b).then(function(b){d=b;return od(a,c)}).then(function(b){v().info("amp-bind","\u2937","\u0394:",b-d,", \u2211:",a.numberOfBindings());return{added:b,removed:d}})}
function rd(a,b,c){var d=a.h;a=a.I;if(d.Worker){var e;e=D(d);Ca(e,e,"amp-worker",wc);d=L(d,"amp-worker");b=xc(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function sd(a,b,c){b=t().createError(b+" "+a.message);b.stack=a.stack;S(b,c);return b}
m.la=function(a){if(a)if("string"==typeof a){var b=ob(this.w,a);t().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=t().assertElement(a),zd(this,b)):t().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else t().info("amp-bind",this.w)};
function zd(a,b){var c=Ib(a.C,function(a){return a.element==b});if(0>c)t().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.C[c].boundProperties;e.forEach(function(b){d.push(Zc(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=z();e.forEach(function(c,d){b[c.property]=a[d]});t().info("amp-bind",b)})}}m.ka=function(a){Zc(this,a,this.w).then(function(a){t().info("amp-bind",a)})};m.wa=function(){return this.M};m.ya=function(){return this.O};(function(a){a.registerServiceForDoc("bind",Wc);a.registerElement("amp-state",Nb);a.registerElement("amp-bind-macro",Kb)})(self.AMP);
})});
//# sourceMappingURL=amp-bind-0.1.js.map

